### ISSUE TITLE
Run a marathon

### ISSUE THREAD

**Issue by fjaguero** [fjaguero/Life#2]
![marathon](https://cloud.githubusercontent.com/assets/716123/12081489/df98f3f2-b27a-11e5-9fdb-38161979c73e.jpg)

My first official run was [back in 2014](http://blog.fjaguero.com/my-first-race/) in Valencia. I had some problems when running that 15k, I wasn't ready but a lesson was learnt that day. :smile: 
- [x] 5k
- [x] 10k
- [x] 15k
- [ ] 21k
- [ ] 42k

**Comment by Kikobeats** [comment]
c'mon!

**Comment by fjaguero** [comment]
@Kikobeats Thanks :smile:
